services:
  database:
    image: mariadb:latest
    container_name: database
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: app_db
      MYSQL_USER: app_user
      MYSQL_PASSWORD: app_password
    ports:
      - "3306:3306"
    volumes:
      - ./db_data:/var/lib/mysql
    user: "${USER_ID}:${GROUP_ID}"
    networks:
      - app_network

  php:
    build: ./php
    container_name: php-fpm
    restart: unless-stopped
    environment:
      APP_DB_HOST: database
      APP_DB_USER: app_user
      APP_DB_PASSWORD: app_password
      APP_DB_NAME: app_db
    volumes:
      - ./app_data:/var/www/html
    depends_on:
      - database
    networks:
      - app_network

  webserver:
    image: nginx:latest
    container_name: webserver
    restart: unless-stopped
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./app_data:/var/www/html
    ports:
      - "80:80"
    depends_on:
      - php
    networks:
      - app_network

networks:
  app_network:
